### ISSUE TITLE
why did you decide to abandon fox in favor of qt?

### ISSUE THREAD

**Issue by MagicalDrizzle** [drfiemost/musiqt#8]
I'm just curious

**Comment by drfiemost** [comment]
That was a long time ago, can't remember correctly but I think it was due to Fox lagging behind, like not supporting xcb on linux and other stuff. It had some strong points but overall Qt is more modern and featureful, and made it easy to add new features such as MPRIS and Last.fm support.
Also Qt is widely used and available.

**Comment by MagicalDrizzle** [comment]
I see ^^
